const tailwindcss = require('tailwindcss');
const mix = require('laravel-mix');

mix   .js('./src/assets/js/theme.js', 'theme/assets')
  // .js('./src/assets/js/customers.js', 'theme/assets')
  // .js('./src/assets/js/details-modal.js', 'theme/assets')
  // .js('./src/assets/js/details-disclosure.js', 'theme/assets')
  // .js('./src/assets/js/predictive-search.js', 'theme/assets')  
  // .js('./src/assets/js/selling-plan.js', 'theme/assets')    
   .sass('./src/assets/scss/theme.scss', 'theme/assets')
  .js('./src/assets/js/product-form.js', 'theme/assets')  
  // .sass('./src/assets/scss/page.scss', 'theme/assets')
  // .sass('./src/assets/scss/product.scss', 'theme/assets')
  .sass('./src/assets/scss/header.scss', 'theme/assets')
  .sass('./src/assets/scss/footer.scss', 'theme/assets')
  .sass('./src/assets/scss/featured-product-list.scss', 'theme/assets')  
  .sass('./src/assets/scss/product-banner.scss', 'theme/assets')    
  .sass('./src/assets/scss/pdp-navigation-bar.scss', 'theme/assets')      
  .sass('./src/assets/scss/hero-banner.scss', 'theme/assets')
  .sass('./src/assets/scss/marquee.scss', 'theme/assets')  
  .sass('./src/assets/scss/home-blog-list.scss', 'theme/assets')    
  .sass('./src/assets/scss/product-details.scss', 'theme/assets')
  .sass('./src/assets/scss/home-our-best-sellers.scss', 'theme/assets')
  .sass('./src/assets/scss/mini-cart.scss', 'theme/assets')
  .sass('./src/assets/scss/search-drawer.scss', 'theme/assets')  
  .sass('./src/assets/scss/blog-details.scss', 'theme/assets')  
  .sass('./src/assets/scss/review.scss', 'theme/assets')    
  .sass('./src/assets/scss/real-people-section.scss', 'theme/assets')      
  .sass('./src/assets/scss/main-review-banner-section.scss', 'theme/assets')        
  .sass('./src/assets/scss/ugc-section.scss', 'theme/assets')          
  .sass('./src/assets/scss/home-logo-sec.scss', 'theme/assets')            
  .sass('./src/assets/scss/login.scss', 'theme/assets')
  .sass('./src/assets/scss/account.scss', 'theme/assets')
  .sass('./src/assets/scss/rich-text-section.scss', 'theme/assets')
  .sass('./src/assets/scss/multi-column.scss', 'theme/assets')
  .sass('./src/assets/scss/subscribe-section.scss', 'theme/assets')
  .sass('./src/assets/scss/featured-product.scss', 'theme/assets')
  .sass('./src/assets/scss/slideshow.scss', 'theme/assets')
  .sass('./src/assets/scss/instagram-slider.scss', 'theme/assets')
  .sass('./src/assets/scss/search-page.scss', 'theme/assets')
  .sass('./src/assets/scss/product-recommendations.scss', 'theme/assets')
  .sass('./src/assets/scss/product-listing.scss', 'theme/assets')
  .sass('./src/assets/scss/promo-sec.scss', 'theme/assets')
  .sass('./src/assets/scss/ingredients-list.scss', 'theme/assets')
  .sass('./src/assets/scss/content-drawer.scss', 'theme/assets')
  .sass('./src/assets/scss/ingredients-features.scss', 'theme/assets')
  .sass('./src/assets/scss/about.scss', 'theme/assets')
  .sass('./src/assets/scss/about-founder.scss', 'theme/assets')
  .sass('./src/assets/scss/inner-banner.scss', 'theme/assets')
  .sass('./src/assets/scss/faq-template.scss', 'theme/assets')
  .sass('./src/assets/scss/contact-us.scss', 'theme/assets')


  .options({
    processCssUrls: false,
    postCss: [ tailwindcss('./tailwind.config.js') ],
  });